"""review.is_approved

Revision ID: 27aba7460739
Revises: 9c3ca9bb729f
Create Date: 2023-09-08 23:48:06.752745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27aba7460739'
down_revision = '9c3ca9bb729f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
